### ISSUE TITLE
Icons for shields and armor are broken

### ISSUE THREAD

**Issue by jamakkon** [Foxfyre/expanse#26]
**Describe the bug**
When creating new shield and armor items, the icon is broken.

**To Reproduce**
1. Go to 'Items Directory'
2. Click on 'Create Item'
3. Type in name 'Foobar'
4. Select type 'Shield' (or 'armor')
5. Click on 'Create new item'
6. See error: The new item appears in the directory with broken icon.

**Expected behavior**
The new item should have the correct icon. 

In the new item JSON export, the path for the image reads `"systems/expanse/ui/item-img/item-shield.png"`. In the project directory, the icon name starts with capital letter thus creating mismatching path: `[Item-shield.png](https://github.com/Foxfyre/expanse/blob/main/ui/item-img/Item-shield.png)`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Browser: Firefox
 - Version: 99
 - The Expanse RPG (AGE): 0.8.2
 -  Foundry VTT: v9 (build 268)

**Comment by Foxfyre** [comment]
Issue solved in 0.8.3

**Comment by Lebo77** [comment]
Is it? I am on 0.8.4 and it looks like this:
![image](https://user-images.githubusercontent.com/57055109/166106911-d0d59f90-9a0b-490a-9506-d928fc1dfae5.png)

**Comment by Foxfyre** [comment]
Is that from existing items or new?

**Comment by Lebo77** [comment]
Both:
[image: image.png]

The Light Armor (TEST!) item was created since the last screenshot.

Oh, and just as a heads up, when creating new items, "armor" is the only
one of the "Type" options that is not capitalized. Not a bug, but thought
you might want to know just for consistency's sake.

Thanks for working on and improving this. It's been a HUGE help in running
our game!
